CREATE TABLE SERVICE (
    product_id INT PRIMARY KEY,
    account_category_description VARCHAR(255),
    account_class_flag CHAR(1),
    account_status CHAR(1),
    account_open_dt DATE,
    collaborator_id INT,
    collaborator_contact VARCHAR(100),
    collaborator_name VARCHAR(100),
    account_payment_id INT,
    service_description VARCHAR(255),
    product_open_dt DATE,
    product_value DECIMAL(10, 2),
    service_isProcessed CHAR(1),
    product_class_flag CHAR(1),
    product_center_id INT,
    product_center_name VARCHAR(100),
    product_value_flag CHAR(1),
    isVIP CHAR(1),
    payment_cod INT,
    account_center_id INT,
    product_charge_value DECIMAL(10, 2),
    FOREIGN KEY (account_center_id) REFERENCES ACCOUNT(account_id)
);