CREATE TABLE EXPENSES (
    account_id INT PRIMARY KEY,
    expenses_status CHAR(1),
    expense_class_flag CHAR(1),
    REC_cod INT,
    REC_client_name VARCHAR(100),
    REC_social_name VARCHAR(100),
    expense_description VARCHAR(255),
    OCC_isProcessed CHAR(1),
    OCC_isPaid CHAR(1),
    OCC_expense_isProcessed CHAR(1),
    expense_due_date DATE,
    expense_open_dt DATE,
    account_destination INT,
    expense_destination INT,
    collaborator_id INT,
    payment_method_id INT,
    payment_method_status CHAR(1),
    expense_value DECIMAL(10, 2),
    expense_cod INT,
    expense_center_id INT,
    expense_center_name VARCHAR(100),
    expense_center_description VARCHAR(255),
    is_expense_flag CHAR(1),
    invoice_category_value DECIMAL(10, 2),
    account_destination_id INT,
    invoice_value DECIMAL(10, 2),
    payment_method_status CHAR(1),
    FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id)
);